version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan serve --host 0
        depends_on:
            - mysql
        ports:
            - 8000:8000
        volumes:
            - .:/workspace
        working_dir: /workspace
    mysql:
        platform: linux/x86_64
        image: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: laravel_memo_app_development
        ports:
            - 3306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
